services:
  web:
    build:
      context: .
    volumes:
      - .:/app:cached
    ports:
      - 8080:8080
    working_dir: /app
    tty: true
    stdin_open: true
    stop_grace_period: 2s
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=123

  postgres:
    image: postgres:15
    container_name: ev_web_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:
